//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moviit.Infrastructure.Data.Persistence
{
    using Moviit.Infrastructure.Data.Entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MINISEntities : DbContext
    {
        public MINISEntities()
            : base("name=MINISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<INGREDIENT> INGREDIENT { get; set; }
        public virtual DbSet<ORDER> ORDER { get; set; }
        public virtual DbSet<ORDER_SANDWICH> ORDER_SANDWICH { get; set; }
        public virtual DbSet<ORDER_STATE> ORDER_STATE { get; set; }
        public virtual DbSet<SANDWICH> SANDWICH { get; set; }
        public virtual DbSet<SANDWICH_CUT_TYPE> SANDWICH_CUT_TYPE { get; set; }
        public virtual DbSet<SANDWICH_INGREDIENT> SANDWICH_INGREDIENT { get; set; }
        public virtual DbSet<SANDWICH_TYPE> SANDWICH_TYPE { get; set; }
    }
}
