//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moviit.Services.BaseServices.Faulting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FaultMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FaultMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moviit.Services.BaseServices.Faulting.Resources.FaultMessages", typeof(FaultMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled or catastrophic exception has occurred. Please check the service logs for more details..
        /// </summary>
        internal static string FaultMessage1000 {
            get {
                return ResourceManager.GetString("FaultMessage1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation was badly configured. A list of fields could not be found..
        /// </summary>
        internal static string FaultMessage1001 {
            get {
                return ResourceManager.GetString("FaultMessage1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing mandatory fields for operation {0}..
        /// </summary>
        internal static string FaultMessage1002 {
            get {
                return ResourceManager.GetString("FaultMessage1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation was badly configured. The field {0} doesn&apos;t exist..
        /// </summary>
        internal static string FaultMessage1003 {
            get {
                return ResourceManager.GetString("FaultMessage1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing fields for operation {0}..
        /// </summary>
        internal static string FaultMessage1004 {
            get {
                return ResourceManager.GetString("FaultMessage1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields were not in a valid email format for operation {0}..
        /// </summary>
        internal static string FaultMessage1005 {
            get {
                return ResourceManager.GetString("FaultMessage1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation was badly configured. The field to validate {0} doesn&apos;t exist..
        /// </summary>
        internal static string FaultMessage1006 {
            get {
                return ResourceManager.GetString("FaultMessage1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation of value types for at least one of the input parameters is not supported..
        /// </summary>
        internal static string FaultMessage1007 {
            get {
                return ResourceManager.GetString("FaultMessage1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare validation failed for operation {0} and parameters {1} and {2}..
        /// </summary>
        internal static string FaultMessage1008 {
            get {
                return ResourceManager.GetString("FaultMessage1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input DTO with errors in fields..
        /// </summary>
        internal static string FaultMessage1009 {
            get {
                return ResourceManager.GetString("FaultMessage1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing DTOValidator, cannot create Type {0} from loaded assemblies..
        /// </summary>
        internal static string FaultMessage1010 {
            get {
                return ResourceManager.GetString("FaultMessage1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Enumeration Value Exception: {0}..
        /// </summary>
        internal static string FaultMessage1011 {
            get {
                return ResourceManager.GetString("FaultMessage1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid RUT for operation {0}..
        /// </summary>
        internal static string FaultMessage1012 {
            get {
                return ResourceManager.GetString("FaultMessage1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation was badly configured. The Type {0} doesn&apos;t have a Validate method..
        /// </summary>
        internal static string FaultMessage1013 {
            get {
                return ResourceManager.GetString("FaultMessage1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation was badly configured for operation {0}. The input has more than one parameter and no parameter name was given..
        /// </summary>
        internal static string FaultMessage1014 {
            get {
                return ResourceManager.GetString("FaultMessage1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation was badly configured, the compare operator is not supported for the data type {0}..
        /// </summary>
        internal static string FaultMessage1015 {
            get {
                return ResourceManager.GetString("FaultMessage1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing mandatory fields for operation {0}. The fields {1} were present but some or all of the fields {2} were missed..
        /// </summary>
        internal static string FaultMessage1016 {
            get {
                return ResourceManager.GetString("FaultMessage1016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatter was badly configured. A valid replacement could not be found..
        /// </summary>
        internal static string FaultMessage1017 {
            get {
                return ResourceManager.GetString("FaultMessage1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatter was badly configured. Each replacement definition must have exactly two strings..
        /// </summary>
        internal static string FaultMessage1018 {
            get {
                return ResourceManager.GetString("FaultMessage1018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatter was badly configured. The field to be formatted must be provided..
        /// </summary>
        internal static string FaultMessage1019 {
            get {
                return ResourceManager.GetString("FaultMessage1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatter was badly configured. The field {0} doesn&apos;t exist..
        /// </summary>
        internal static string FaultMessage1020 {
            get {
                return ResourceManager.GetString("FaultMessage1020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatter was badly configured. The field {0} is not a string field..
        /// </summary>
        internal static string FaultMessage1021 {
            get {
                return ResourceManager.GetString("FaultMessage1021", resourceCulture);
            }
        }
    }
}
