//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moviit.Infrastructure.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGREDIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INGREDIENT()
        {
            this.SANDWICH_INGREDIENT = new HashSet<SANDWICH_INGREDIENT>();
        }
    
        public int Id { get; set; }
        public string IngredientName { get; set; }
        public byte MachineStackIndex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANDWICH_INGREDIENT> SANDWICH_INGREDIENT { get; set; }
    }
}
