//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moviit.Infrastructure.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANDWICH_CUT_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANDWICH_CUT_TYPE()
        {
            this.SANDWICH_TYPE = new HashSet<SANDWICH_TYPE>();
        }
    
        public int Id { get; set; }
        public string SandwichCutName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANDWICH_TYPE> SANDWICH_TYPE { get; set; }
    }
}
