//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moviit.Infrastructure.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANDWICH_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANDWICH_TYPE()
        {
            this.SANDWICH = new HashSet<SANDWICH>();
        }
    
        public int Id { get; set; }
        public string SandwichTypeName { get; set; }
        public int CutTypeId { get; set; }
        public bool HasSalsa { get; set; }
        public bool SalsaInside { get; set; }
        public bool HasCompression { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANDWICH> SANDWICH { get; set; }
        public virtual SANDWICH_CUT_TYPE SANDWICH_CUT_TYPE { get; set; }
    }
}
