//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moviit.Infrastructure.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANDWICH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANDWICH()
        {
            this.ORDER_SANDWICH = new HashSet<ORDER_SANDWICH>();
            this.SANDWICH_INGREDIENT = new HashSet<SANDWICH_INGREDIENT>();
        }
    
        public int Id { get; set; }
        public string SandwichName { get; set; }
        public int SandwichTypeId { get; set; }
        public decimal Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_SANDWICH> ORDER_SANDWICH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANDWICH_INGREDIENT> SANDWICH_INGREDIENT { get; set; }
        public virtual SANDWICH_TYPE SANDWICH_TYPE { get; set; }
    }
}
