//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moviit.Infrastructure.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANDWICH_INGREDIENT
    {
        public int Id { get; set; }
        public int SandwichId { get; set; }
        public int IngredientId { get; set; }
    
        public virtual INGREDIENT INGREDIENT { get; set; }
        public virtual SANDWICH SANDWICH { get; set; }
    }
}
